### ISSUE TITLE
5.0.2 No longer support Node 16？

### ISSUE THREAD

**Issue by Augenstern-Jcheng** [gjtorikian/isBinaryFile#72]
<img width="1944" alt="error_img" src="https://github.com/gjtorikian/isBinaryFile/assets/75055948/c9a5d900-5c14-470a-819a-218600e1e2d9">

**Comment by gjtorikian** [comment]
Yes, Node 16 is deprecated: https://nodejs.org/en/blog/announcements/nodejs16-eol

either pin to an older version of the package, or upgrade Node (I suggest the latter as it is the wiser option).

**Comment by gjtorikian** [comment]
I hear that, but I don't agree with it, and I program in multiple languages, so I don't constrict myself to the opinions of any one person in any one project.

For me, it's more of an ethical issue: I think it's inappropriate to allow old and deprecated language runtimes to continue to operate in the wild. Your app broke because a patch version changed the major version underneath you? Then your app better upgrade to the major release! Who knows how many security issues (to say nothing of performance improvements) your downstream users are missing out on, because the app is running on a deprecated language version.

Every argument contrary to this boils down to "But what if I don't have time to upgrade my app's language runtime?" Ok: then don't update to a new dependency version, either.

I recognize that a patch version is meant for "when you make backward compatible bug fixes"; but I think the urgency of potential security issues supersedes that mandate.

**Comment by gorner** [comment]
I appreciate your well-considered point of view on the matter. We'll have to agree to disagree. 

Purely for context: I'm iteratively upgrading some long-neglected dependencies in a project so that we _can_ bump Node, this is just a transitive dependency of one of them (which [specifies](https://github.com/ember-cli/ember-cli/blob/v4.12.2/package.json#L99) `^5.0.0`). We can use package.json `overrides` to pin to 5.0.0 for now.
